### ISSUE TITLE
请问如何获取另一种链接的腾讯会议直播直链地址

### ISSUE THREAD

**Issue by cnRicky** [Cloudiver/tencent_meeting#1]
请问这种链接：https://meeting.tencent.com/s/YpP0znz1rafX的腾讯会议直播直链地址怎么获取

**Comment by lilyomo** [comment]
@cnRicky 这个没有抓到包，不知道怎么获取。

**Comment by cnRicky** [comment]
好滴，还是谢谢你了！




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Cloudiver"<notifications@github.com&gt;; 
发送时间: 2020年12月8日(星期二) 下午4:19
收件人: "Cloudiver/tencent_meeting"<tencent_meeting@noreply.github.com&gt;; 
抄送: "Coco"<3191378281@qq.com&gt;; "Mention"<mention@noreply.github.com&gt;; 
主题: Re: [Cloudiver/tencent_meeting] 请问如何获取另一种链接的腾讯会议直播直链地址 (#1)





 
@cnRicky 这个没有抓到包，不知道怎么获取。

**Comment by lilyomo** [comment]
@cnRicky 如果有找到合适的方法，麻烦告知下，谢谢你。😊
