### ISSUE TITLE
疑问

### ISSUE THREAD

**Issue by tingzeh** [Cloudiver/tencent_meeting#3]
大佬，打扰下您，不知道还是否可正常使用呢？我下载后更改了py里的url后运行并没有输出，想问下是不能使用了还是我没正确使用呢？打扰您了，抱歉抱歉(/▽＼)

**Comment by lilyomo** [comment]
@tingzeh 只能是腾讯会议直播的地址，https://meeting.tencent.com/l， 这样开头的地址才是直播，其他地址属于会议模式，目前我不知道如何解决。

**Comment by tingzeh** [comment]
这样啊，好的好的明白了，谢谢您，打扰了抱歉抱歉(/▽＼)
